openapi: 3.1.0

info:
  title: Szpontniki's Firmware API
  version: 0.1.0
  description: API of a LED-managing microcontroller developed by Szpontniki.
  license:
    name: GNU General Public License v3.0
    identifier: GPL-3.0-only
  contact:
    name: Szpontniki
    url: https://github.com/Szpontniki

servers:
  - url: http://localhost:3000
    description: Default development environment URI.

paths:
  /display/color-pixels:
      $ref: './paths/display/color-pixels.yaml'

components:
  schemas:
    Color:
      $ref: './schemas/objects/color.yaml'
    ColorPixelsRequest:
      $ref: './schemas/request-bodies/color-pixels-request.yaml'
